# Prompt {{{
add_newline = false
format = '''
$character
'''
right_format = '''
$directory$all
'''
# }}}

# Azure {{{
[azure]
format = 'via [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
# }}}

# C {{{
[c]
format = 'via [$symbol($version(-$name))]($style) '
symbol = ' '
# }}}

# Character {{{
[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
# }}}

# CMD duration {{{
[cmd_duration]
min_time = 2_000
format = 'took [$duration]($style) '
# }}}

# Directory {{{
[directory]
read_only = ' '
read_only_style = 'bold red'
style = 'bold white'
truncation_symbol = '../'
truncation_length = 3
truncate_to_repo = false
# }}}

# GIT Branch {{{
[git_branch]
always_show_remote = true
format = 'on [$symbol$branch]($style) '
symbol = ' '
style = 'bold purple'
# }}}

# GIT Commit {{{
[git_commit]
format = 'via [$hash$tag]($style) '
tag_disabled = false
style = 'bold purple'
# }}}

# GIT Status {{{
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = '󰁝'
behind = '󰁅'
deleted = ''
diverged = ''
modified = '!'
renamed = ''
staged = ''
stashed = '$'
up_to_date = ''
untracked = '?'
style = 'bold purple'
# }}}

# Hostname {{{
[hostname]
ssh_symbol = ' '
# }}}

# Line break {{{
[line_break]
disabled = false
# }}}

# Lua {{{
[lua]
format = 'via [$symbol($version)]($style) '
symbol = ' '
style = 'bold blue'
# }}}

# Node JS {{{
[nodejs]
symbol = ' '
format = 'via [$symbol($version)]($style) '
style = 'bold green'
# }}}

# Package {{{
[package]
disabled = true
# }}}

# Python {{{
[python]
format = 'via [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = ' '
# }}}

# Rust {{{
[rust]
format = 'via [$symbol($version)]($style) '
symbol = ' '
version_format = '${raw}'
# }}}

# Sudo {{{
[sudo]
disabled = false
format = 'as [su]($style) '
# }}}
