# https://github.com/Skxxtz/sherlock/blob/main/docs/examples/config.toml

[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "kitty"
browser = "/opt/zen-browser-bin/zen-bin %u"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "eur"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 600
gsk_renderer = "cairo"
icon_paths = ["testconfig/icons"]
icon_size = 20
use_base_css = false
opacity = 0.9
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = false
animate = true

[binds]
up = "control-m"
down = "control-n"
left = "control-e"
right = "control-i"
context = "control-c"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/marci/.config/sherlock/config.toml"
css = "/home/marci/.config/sherlock/main.css"
fallback = "/home/user/.config/sherlock/fallback.json"
alias = "/home/user/.config/sherlock/sherlock_alias.json"
ignore = "/home/marci/.config/sherlock/sherlockignore"
actions = "/home/user/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "/home/user/.cache/sherlock/desktop_cache.bin"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = true
opacity = 0.6
edge = "top"

[status_bar]
enable = true

[search_bar_icon]
enable = true
icon = "system-search-symbolic"
icon_back = "sherlock-back"
size = 20
