theme:
  active: "242, 66, 255"
  banner: "242, 66, 255"
  error_border: "255, 0, 0"
  error_text: LightRed
  hint: "100, 50, 255"
  hovered: "150, 30, 255"
  inactive: Gray
  playbar_background: "0, 0, 0"
  playbar_progress: "242, 66, 255"
  playbar_progress_text: "255, 255, 255"
  playbar_text: "255, 255, 255"
  selected: "200, 46, 225"
  text: "255, 255, 255"
  header: "255, 255, 255"

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  tick_rate_milliseconds: 250
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: true
  liked_icon: â™¥
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶
  paused_icon: â¸
  set_window_title: true

keybindings:
  back: "ctrl-q"

  jump_to_album: "a"
  jump_to_artist_album: "A"

  manage_devices: "d"

  decrease_volume: "-"
  increase_volume: "+"

  toggle_playback: " "

  seek_backwards: "<"
  seek_forwards: ">"

  next_track: "n"
  previous_track: "p"

  copy_song_url: "c"
  copy_album_url: "C"

  help: "?"
  search: "/"

  shuffle: "ctrl-s"
  repeat: "r"
  add_item_to_queue: "z"

  audio_analysis: "v"
  basic_view: "B"

  jump_to_context: "o"
